import {StyleSheet} from 'react-native';
import {color} from '../../utility';
import {
  widthPercentageToDP as wp,
  // heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
export default StyleSheet.create({
  chatContainer: {
    backgroundColor: '#f2f1f1',
    borderRadius: 10,
    borderTopLeftRadius: 0,
    marginLeft: 15,
    marginRight: 15,
    elevation: -5,
  },
  chatTxt: {
    color: color.BLACK,
    fontSize: wp(3.2),
    // textAlign: 'right',
    marginVertical: 5,
    fontWeight: '500',
    paddingHorizontal: 12,
    paddingVertical: 3,
  },
  dateTxt: {
    color: '#333',
    fontSize: wp(2.3),
    // marginVertical: 5,
    textAlign: 'left',
    fontWeight: '500',
    paddingHorizontal: 12,
    // paddingVertical: 3,
  },
  arrowRight: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 8,
    borderRightWidth: 0,
    borderBottomWidth: 10,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#f2f1f1',
    transform: [{rotate: '-90deg'}],
    position: 'absolute',
    left: -8,
    top: -1.1,
  },
  arrowLeft: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 0,
    borderRightWidth: 8,
    borderBottomWidth: 10,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#ffeff3',
    transform: [{rotate: '90deg'}],
    position: 'absolute',
    right: -6,
    top: -1.1,
  },
  typingIcon: {
    height: wp(3),
    aspectRatio: 1 / 1,
  },
});
