import {StyleSheet} from 'react-native';
//Responsive Screen
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

const styles = StyleSheet.create({
  followouter: {
    justifyContent: 'center',
    alignItems: 'center',
    width: wp(20),
    paddingHorizontal: wp(3),
    height: hp(4),
    borderRadius: hp(2),
    // backgroundColor: 'dodgerblue',
    borderColor: '#fff',
    // backgroundColor: '#bc0f17',
    backgroundColor: '#fff',
    // marginTop: wp(5),
  },
  unfollowouter: {
    justifyContent: 'center',
    alignItems: 'center',
    width: wp(20),
    paddingHorizontal: wp(3),
    height: hp(4),
    borderRadius: hp(2),
    borderWidth: 1,
    borderColor: '#fff',
    // backgroundColor: '#fff',
  },
  oldPrice: {
    fontSize: wp(3),
    color: '#a04f06',
    textDecorationLine: 'line-through',
    marginHorizontal: wp(1),
  },
  newPrice: {
    fontSize: wp(3),
    color: '#fffcd5',
    fontWeight: '700',
    marginHorizontal: wp(1),
  },
  ChatPrice: {
    fontSize: wp(3),
    color: '#333',
    fontWeight: '700',
    marginHorizontal: wp(1),
  },
  linearGradient: {
    height: hp(25),
    borderBottomRightRadius: wp(10),
    justifyContent: 'center',
  },
  astroInfoContainer: {
    padding: wp(3),
    marginBottom: hp(8),
    flexDirection: 'row',
    alignItems: 'center',
  },
  astroPhoto: {
    width: wp(18),
    aspectRatio: 1 / 1,
    borderRadius: wp(9),
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    marginRight: wp(2),
  },
  astroName: {
    fontSize: wp(4),
    fontWeight: '700',
    color: '#fff',
    marginBottom: wp(1),
  },
  followButton: {
    height: hp(4),
    backgroundColor: '#fff',
    borderRadius: hp(2),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: wp(3),
  },
  postButton: {
    height: hp(4),
    borderColor: '#fff',
    borderWidth: 1,
    borderRadius: hp(2),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: wp(3),
    marginLeft: wp(2),
  },
  infoContainer: {
    backgroundColor: '#fff',
    elevation: 5,
    flexDirection: 'row',
    paddingVertical: wp(5),
    marginHorizontal: wp(3),
    marginBottom: wp(3),
    marginTop: hp(-8),
    borderRadius: 5,
  },
  value: {
    fontSize: wp(5.5),
    fontWeight: '700',
    color: '#fd6c33',
    marginBottom: wp(1),
  },

  headings: {
    fontSize: wp(4),
    fontWeight: '700',
    color: '#333',
    marginBottom: wp(1),
  },
  VerifiedContainer: {
    // backgroundColor: '#fd6c33',
    // width: wp(5),
    // height: wp(10),
    // aspectRatio: 1 / 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verifiedIcon: {
    // backgroundColor: '#fd6c33',
    // width: wp(5),
    height: wp(10),
    aspectRatio: 1 / 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  separator: {
    width: wp(2),
  },
  reviewSeparator: {
    height: 1,
    backgroundColor: '#00000020',
    marginVertical: wp(1),
  },
  chatButton: {
    backgroundColor: '#fd6c33',
    height: hp(7),
    alignItems: 'center',
  },
  liveButton: {
    backgroundColor: '#bc0f17',
    height: hp(7),
    alignItems: 'center',
  },
  callButton: {
    backgroundColor: '#fd8933',
    height: hp(7),
    alignItems: 'center',
  },
  iconRow: {
    marginRight: wp(2),
  },
  modalContainer: {
    backgroundColor: '#00000080',
    position: 'absolute',
    top: 0,
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
  },
  screenContainer: {
    backgroundColor: '#fd6c33',
    position: 'absolute',
    top: 0,
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
  },
  screenContainer2: {
    flex: 1,
  },
  popupContainer: {
    backgroundColor: '#fffdc5',
    height: hp(40),
    borderTopLeftRadius: wp(3),
    borderTopRightRadius: wp(3),
    padding: wp(3),
  },

  popupContainer2: {
    backgroundColor: '#00000080',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },

  mainContent: {
    backgroundColor: '#fffdc5',
    height: hp(70),
    width: wp(80),
    borderRadius: wp(3),
    padding: wp(3),
  },
  listContainerMain: {
    borderWidth: 1,
    borderColor: '#cccccc',
    padding: wp(2),
    marginTop: wp(3),
    marginBottom: 'auto',
  },
  listContainerMain2: {
    borderWidth: 1,
    borderColor: '#cccccc',
    padding: wp(2),
    marginTop: wp(3),
    // marginBottom: 'auto',
    alignItems: 'center',
  },
  listContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp(0),
    paddingVertical: wp(1),
  },
  popupButton: {
    backgroundColor: '#bc0f17',
    padding: wp(3),
    // marginTop: hp(10),
    flexDirection: 'row',
    justifyContent: 'center',
  },
  popupButton2: {
    backgroundColor: '#fd6c33',
    padding: wp(3),
    // marginTop: hp(10),
    flexDirection: 'row',
    justifyContent: 'center',
  },
  popupButtonText: {
    color: '#fffdc5',
    fontSize: wp(3.5),
    fontWeight: '700',
  },
  allSetIcon: {
    height: wp(12),
    aspectRatio: 1 / 1,
    alignSelf: 'center',
    marginTop: hp(3),
  },
  astroImage: {
    width: wp(12),
    aspectRatio: 1 / 1,
    marginHorizontal: wp(3),
    borderRadius: hp(12),
  },
  line: {
    width: wp(6),
    aspectRatio: 1 / 1,
  },
  close: {
    position: 'absolute',
    right: wp(2),
    top: wp(4),
  },
  // busyBlock: {
  //   height: hp(6),
  //   backgroundColor: '#52361b',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  // },
  busyButton: {
    backgroundColor: '#ffbf00',
    alignItems: 'center',
    paddingVertical: wp(2.5),
    marginTop: wp(2),
    flexDirection: 'row',
    justifyContent: 'center',
    // margin: wp(2),
  },
});
export default styles;
