import {Dimensions, StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
const dimensions = {
  width: Dimensions.get('window').width,
  height: Dimensions.get('window').height,
};

export default StyleSheet.create({
  max: {
    flex: 1,
  },
  buttonHolder: {
    width: wp(92),
    bottom: hp(2),
    borderRadius: 50,
    marginHorizontal: wp(4),
    paddingVertical: wp(3),
    alignItems: 'center',
    // borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    position: 'absolute',
    zIndex: 9999,
    backgroundColor: '#ffffff99',
  },
  button: {
    // paddingHorizontal: wp(10),
    // paddingVertical: wp(10),
    justifyContent: 'space-between',
    borderRadius: 25,
  },
  Iconbutton: {
    // paddingHorizontal: wp(10),
    // paddingVertical: wp(10),
    justifyContent: 'space-between',
    borderRadius: 25,
    // flex: 1,
  },
  buttonText: {
    // color: '#fff',
    width: wp(15),
    height: wp(15),
    // aspectRatio: 1 / 1,
  },
  buttonIcon: {
    // color: '#fff',
    width: wp(7),
    height: wp(7),
    // aspectRatio: 1 / 1,
  },
  fullView: {
    width: dimensions.width,
    height: dimensions.height,
  },
  remoteContainer: {
    width: wp(32),
    height: hp(22),
    position: 'absolute',
    top: hp(4),
    right: wp(3),
    borderRadius: wp(4),
    // borderWidth: 2,
    // borderColor: 'red',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  remote: {
    width: wp(32),
    height: hp(22),
    borderRadius: 25,
    marginHorizontal: 2.5,
  },
  noUserText: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    color: '#0093E9',
  },
  container: {
    flex: 1,
    backgroundColor: '#fffcd5',
  },
  liveStreamButton: {
    backgroundColor: '#34495e',
    alignItems: 'center',
    paddingVertical: 15,
    borderRadius: 10,
    marginHorizontal: 25,
    marginBottom: 15,
  },
  textButton: {
    color: 'white',
    fontSize: 25,
  },
  input: {
    backgroundColor: 'white',
    borderRadius: 10,
    paddingVertical: 20,
    paddingHorizontal: 20,
    marginVertical: 20,
    marginHorizontal: 25,
    fontSize: 23,
    fontWeight: '600',
  },
  flatList: {
    padding: wp(3),
  },
  welcomeText: {
    fontSize: wp(3.5),
    color: '#333',
    fontWeight: 'bold',
  },
  welcomeText2: {
    fontSize: wp(4),
    color: '#333',
    fontWeight: 'bold',
  },
  title: {
    fontSize: wp(4),
    color: 'black',
    fontWeight: '700',
    marginHorizontal: wp(3),
  },
  separator: {
    height: wp(2),
  },
  listContainer: {
    padding: wp(2),
  },
  bcgImg: {
    flex: 1,
    width: wp(100),
    height: hp(100),
  },
  buttonStyle: {
    position: 'absolute',
    bottom: hp(15),
    left: wp(4),
    flexDirection: 'row',
    // borderWidth: 1,
    backgroundColor: '#ffffff99',
    borderRadius: 50,
    alignItems: 'center',

    paddingRight: wp(3),
  },
  profileButton: {
    padding: wp(2),
    borderRadius: 50,
  },

  profileButton2: {
    height: wp(59),
    width: wp(59),
    borderRadius: wp(29.5),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8e9f9',
  },
  border2: {
    height: wp(56),
    width: wp(56),
    borderRadius: wp(28),
    alignItems: 'center',
    justifyContent: 'center',
    // padding: wp(2),
    backgroundColor: '#f8e2f4',
  },
  border3: {
    height: wp(53),
    width: wp(53),
    borderRadius: wp(26.5),
    alignItems: 'center',
    justifyContent: 'center',
    // padding: wp(2),
    backgroundColor: '#f8dbef',
  },
  border4: {
    height: wp(50),
    width: wp(50),
    borderRadius: wp(25),
    alignItems: 'center',
    justifyContent: 'center',
    // padding: wp(2),
    backgroundColor: '#f9c5e010',
    borderWidth: 5,
    borderColor: '#f9c5e0',
  },
  userImage21: {
    height: wp(47),
    aspectRatio: 1 / 1,
    borderRadius: wp(23.5),
    // borderWidth: 1,
    // marginTop: 20,
    // borderColor: '#ccc',
  },
  endIcon: {
    height: hp(3.5),
    aspectRatio: 1 / 1,
    borderRadius: hp(2),
  },
  endIcon2: {
    height: hp(5),
    aspectRatio: 1 / 1,
    borderRadius: hp(2),
  },
  liveCount: {
    color: '#333',
    fontSize: wp(4),
    marginLeft: wp(1),
    marginRight: wp(2),
    marginBottom: wp(-2),
  },
  buttonEnd: {
    backgroundColor: '#ffffff99',
    width: wp(12),
    height: wp(12),
    borderRadius: wp(6),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: wp(4),
    bottom: hp(22),
  },
  indicator: {
    backgroundColor: 'red',
    height: 8,
    width: 8,
    borderRadius: 4,
    marginRight: wp(2),
  },
  callDialerContainer: {
    borderWidth: 1,
    backgroundColor: '#00000095',
    borderRadius: 50,
    position: 'absolute',
    top: hp(16),
    left: wp(1),
    zIndex: 99999,
  },
  DialerContainer: {
    flexDirection: 'row',
    padding: wp(2),
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  flipIcon: {
    backgroundColor: '#fff9',
    width: wp(12),
    height: wp(12),
    borderRadius: wp(6),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: wp(4),
    bottom: hp(14),
  },
  flipIconImage: {
    height: wp(6),
    aspectRatio: 1 / 1,
  },
});
