import {Dimensions, StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

const dimensions = {
  width: Dimensions.get('window').width,
  height: Dimensions.get('window').height,
};

const {width: screenWidth} = Dimensions.get('window');
export default StyleSheet.create({
  liveCount: {
    color: '#fff',
    fontSize: wp(3.5),
    marginLeft: wp(1),
    fontWeight: '700',
  },
  liveCount2: {
    color: '#fff',
    fontSize: wp(2.8),
    marginLeft: wp(1),
    fontWeight: '400',
  },
  max: {
    flex: 1,
  },
  bcgImg: {
    flex: 1,
    width: wp(100),
  },
  buttonHolder: {
    height: 100,
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  buttonStyle: {
    position: 'absolute',
    top: wp(2),
    left: wp(2),
    flexDirection: 'row',
    borderWidth: 1,
    backgroundColor: '#00000095',
    borderRadius: 50,
    alignItems: 'center',
    paddingRight: wp(3),
  },
  profileButton: {
    padding: wp(1),
    borderRadius: 50,
    borderWidth: 3,
    borderColor: '#fff',
    marginRight: wp(1),
  },
  button: {
    padding: wp(2),
    borderRadius: 50,
  },
  buttonEnd: {
    position: 'absolute',
    top: 3,
    right: 0,
    padding: wp(2),
    borderRadius: 50,
  },
  buttonText: {
    color: '#fff',
  },
  fullView: {
    width: dimensions.width,
    height: dimensions.height - 100,
  },
  remoteContainer: {
    width: '100%',
    height: 150,
    position: 'absolute',
    top: 0,
    left: 0,
  },
  remote: {
    width: dimensions.width,
    height: dimensions.height,
    // marginHorizontal: wp(2),
  },
  noUserText: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    color: '#0093E9',
  },
  endIcon: {
    height: hp(4.5),
    aspectRatio: 1 / 1,
    borderRadius: hp(2.25),
  },

  chatContainer: {
    width: wp(100),
    paddingVertical: wp(1),
    paddingHorizontal: wp(4),
    flexDirection: 'row',
    alignItems: 'center',
    // width: wp(100),
    position: 'absolute',
    bottom: 0,
    marginHorizontal: wp(0),
    zIndex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
  },
  input: {
    flex: 1,
    fontSize: wp(3.5),
    color: '#333',
    // paddingHorizontal: wp(2),
  },
  chatBox: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    height: hp(5),
    color: '#333',
    // borderWidth: 1,
    // borderColor: '#6668',
    // backgroundColor: '#00000060',
    borderRadius: wp(10),
    // elevation: 8,
  },
  sndIcon: {
    height: hp(3.5),
    aspectRatio: 1 / 1,
  },
  extContainer: {
    // flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: wp(2),
  },
  extraIcn: {
    // backgroundColor: '#00000095',
    borderRadius: wp(8),
    // marginHorizontal: wp(0.5),
    padding: wp(0.7),
    marginLeft: wp(2),
  },
  shareIcn: {
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    height: wp(10),
    width: wp(10),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    // marginHorizontal: wp(0.5),
    padding: wp(0.7),
    marginLeft: wp(2),
    position: 'absolute',
    bottom: hp(7.5),
    right: wp(3),
  },
  shareIcon: {
    height: wp(4.5),
    aspectRatio: 1 / 1,
  },
  floatIconContainer: {
    flex: 1,
    // height: wp(3),
    // width: wp(10),
    bottom: 0,
    left: wp(0),
    // right: 0,
    position: 'absolute',
  },
  floatIcon: {
    height: wp(100),
    aspectRatio: 1 / 1,
  },
  extIcon: {
    height: hp(3.5),
    aspectRatio: 1 / 1,
  },
  graceDialerContainer: {
    // borderRadius: 50,
    width: wp(100),
    backgroundColor: '#a04f06',
    position: 'absolute',
    top: hp(7.5),
    // left: wp(1),
    zIndex: 99999,
  },
  callDialerContainer: {
    borderWidth: 1,
    backgroundColor: '#00000095',
    borderRadius: 50,
    position: 'absolute',
    top: hp(16),
    left: wp(1),
    zIndex: 99999,
  },
  callDialerContainer3: {
    borderWidth: 1,
    backgroundColor: '#00000095',
    borderRadius: 50,
    position: 'absolute',
    top: hp(16),
    left: wp(1),
    zIndex: 99999,
    paddingHorizontal: wp(2),
    paddingVertical: wp(1),
  },
  callDialerContainer2: {
    borderWidth: 1,
    backgroundColor: '#00000095',
    borderRadius: 50,
    position: 'absolute',
    top: hp(25),
    left: wp(1),
    zIndex: 99999,
  },
  DialerContainer: {
    flexDirection: 'row',
    padding: wp(2),
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  DialerContainer2: {
    flexDirection: 'row',
    padding: wp(2),
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  callContainer21: {
    flexDirection: 'row',
    position: 'absolute',
    top: hp(12),
    left: wp(1),
    zIndex: 999999,
  },
  callContainer22: {
    borderWidth: 1,
    borderRadius: 50,
    backgroundColor: '#00000095',
    flexDirection: 'row',
    position: 'absolute',
    top: hp(25),
    left: wp(3),
    zIndex: 999999,
  },
  callContainer: {
    position: 'absolute',
    bottom: hp(16),
    right: wp(3),
    zIndex: 99999,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  callIcn: {
    height: hp(9),
    aspectRatio: 1 / 1,
  },
  priceContainer: {
    position: 'absolute',
    zIndex: 9999.99,
    top: 8,
    right: 12,
  },
  callPrice: {
    fontSize: wp(3.8),
    fontWeight: '700',
    textAlign: 'center',
    color: '#fff',
  },
  textFormat: {
    position: 'relative',
    fontSize: wp(2.3),
    fontWeight: '400',
    textAlign: 'center',
    marginTop: -2,
    // marginRight: 3,
    color: '#fff',
  },
  callIcn2: {
    width: hp(5),
    aspectRatio: 1 / 1,
    borderRadius: 50,
  },
  callIcn3: {
    width: hp(8),
    aspectRatio: 1 / 1,
    borderRadius: 50,
  },
  ofrContainer: {
    position: 'absolute',
    bottom: hp(28),
    right: wp(3),
    zIndex: 99999,
  },
  ofrIcn: {
    height: hp(8),
    aspectRatio: 1 / 1,
  },

  loaderContainer: {
    backgroundColor: '#ccc',
  },

  lottie: {
    width: wp(100),
    height: wp(100),
    // borderWidth: 1,
    transform: [{rotate: '180deg'}],
    // marginTop: hp(30),
    // position: 'absolute',
    // top: 0,
    // left: 0,
    // right: 0,
    // alignSelf: 'center',
  },

  //* chat message message for live chat

  wrapListMessages: {
    position: 'absolute',
    bottom: hp(7),
    left: 0,
    right: 0,
    height: screenWidth / 1.5,
    width: screenWidth / 1.3,
  },
  chatItem: {
    flex: 1,
    flexDirection: 'row',
    // backgroundColor: '#0006',
    padding: wp(1),
    alignItems: 'center',
    marginHorizontal: wp(2),
    marginVertical: wp(0.5),
    borderRadius: hp(5),
  },
  messageItem: {
    flex: 1,
    flexDirection: 'column',
    marginHorizontal: wp(1),
    paddingVertical: wp(2),
    paddingHorizontal: wp(3),
    borderRadius: wp(6),
    borderTopLeftRadius: 0,
    backgroundColor: '#ffffff99',
    marginLeft: wp(2),
  },
  avatar: {
    borderRadius: hp(2.5),
    height: hp(5),
    aspectRatio: 1 / 1,
  },
  name: {
    fontSize: wp(2.8),
    color: '#333',
    fontWeight: '700',
  },
  content: {
    fontSize: wp(3.2),
    fontWeight: '400',
    marginTop: 0,
    color: '#333',
  },

  //*popup screen button
  followouter: {
    justifyContent: 'center',
    alignItems: 'center',
    width: wp(20),
    paddingHorizontal: wp(3),
    height: hp(4),
    borderRadius: hp(2),
    // backgroundColor: 'dodgerblue',
    borderColor: '#fff',
    // backgroundColor: '#bc0f17',
    backgroundColor: '#fff',
    // marginTop: wp(5),
  },
  unfollowouter: {
    justifyContent: 'center',
    alignItems: 'center',
    width: wp(20),
    paddingHorizontal: wp(3),
    height: hp(4),
    borderRadius: hp(2),
    borderWidth: 1,
    borderColor: '#fff',
    // backgroundColor: '#fff',
  },
  oldPrice: {
    fontSize: wp(3),
    color: '#a04f06',
    textDecorationLine: 'line-through',
    marginHorizontal: wp(1),
  },
  newPrice: {
    fontSize: wp(3),
    color: '#fffcd5',
    fontWeight: '700',
    marginHorizontal: wp(1),
  },
  linearGradient: {
    height: hp(25),
    borderBottomRightRadius: wp(10),
    justifyContent: 'center',
  },
  astroInfoContainer: {
    padding: wp(3),
    marginBottom: hp(8),
    flexDirection: 'row',
    alignItems: 'center',
  },
  astroPhoto: {
    width: wp(18),
    aspectRatio: 1 / 1,
    borderRadius: wp(9),
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    marginRight: wp(2),
  },
  astroName: {
    fontSize: wp(4),
    fontWeight: '700',
    color: '#fff',
    marginBottom: wp(1),
  },
  followButton: {
    height: hp(4),
    backgroundColor: '#fff',
    borderRadius: hp(2),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: wp(3),
  },
  postButton: {
    height: hp(4),
    borderColor: '#fff',
    borderWidth: 1,
    borderRadius: hp(2),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: wp(3),
    marginLeft: wp(2),
  },
  infoContainer: {
    backgroundColor: '#fff',
    elevation: 5,
    flexDirection: 'row',
    paddingVertical: wp(5),
    marginHorizontal: wp(3),
    marginBottom: wp(3),
    marginTop: hp(-8),
    borderRadius: 5,
  },
  value: {
    fontSize: wp(5.5),
    fontWeight: '700',
    color: '#fd6c33',
    marginBottom: wp(1),
  },

  headings: {
    fontSize: wp(4),
    fontWeight: '700',
    color: '#333',
    marginBottom: wp(1),
  },
  VerifiedContainer: {
    // backgroundColor: '#fd6c33',
    // width: wp(5),
    // height: wp(10),
    // aspectRatio: 1 / 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verifiedIcon: {
    // backgroundColor: '#fd6c33',
    // width: wp(5),
    height: wp(10),
    aspectRatio: 1 / 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  separator: {
    width: wp(2),
  },
  reviewSeparator: {
    height: 1,
    backgroundColor: '#00000020',
    marginVertical: wp(1),
  },
  chatButton: {
    backgroundColor: '#fd6c33',
    height: hp(7),
    alignItems: 'center',
  },
  callButton: {
    backgroundColor: '#fd8933',
    height: hp(7),
    alignItems: 'center',
  },
  iconRow: {
    marginRight: wp(2),
  },
  modalContainer: {
    backgroundColor: '#00000080',
    position: 'absolute',
    top: 0,
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
    zIndex: 9999999.99,
  },
  screenContainer: {
    backgroundColor: '#fd6c33',
    position: 'absolute',
    top: 0,
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
  },
  screenContainer2: {
    flex: 1,
  },
  popupContainer: {
    backgroundColor: '#fff',
    maxHeight: hp(40),
    borderTopLeftRadius: wp(3),
    borderTopRightRadius: wp(3),
    padding: wp(3),
  },
  popupKundaliContainer: {
    backgroundColor: '#fff',
    maxHeight: hp(55),
    borderTopLeftRadius: wp(3),
    borderTopRightRadius: wp(3),
    padding: wp(3),
  },

  popupContainer2: {
    backgroundColor: '#00000080',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },

  mainContent: {
    backgroundColor: '#fffdc5',
    height: hp(70),
    width: wp(80),
    borderRadius: wp(3),
    padding: wp(3),
  },
  listContainerMain: {
    // borderWidth: 1,
    borderColor: '#cccccc',
    // padding: wp(2),
    // marginTop: wp(3),
    // marginBottom: 'auto',
  },
  listContainerMain2: {
    borderWidth: 1,
    borderColor: '#cccccc',
    paddingVertical: wp(2),
    marginTop: wp(3),
    // marginBottom: 'auto',
    alignItems: 'center',
  },
  listContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // paddingHorizontal: wp(2),
    paddingVertical: wp(1),
  },
  popupButton: {
    backgroundColor: '#f65472',
    padding: wp(3),
    marginTop: hp(2),
    flexDirection: 'row',
    justifyContent: 'center',
  },
  popupButton2: {
    backgroundColor: '#f2f1f1',
    padding: wp(3),
    marginTop: 3,
    flexDirection: 'row',
  },
  popupButton00: {
    backgroundColor: '#f65472',
    padding: wp(3),
    marginTop: 3,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  popupButtonText: {
    color: '#fff',
    fontSize: wp(3.5),
    fontWeight: '700',
  },
  popupButtonText2: {
    color: '#333',
    fontSize: wp(3.5),
    fontWeight: '700',
  },
  allSetIcon: {
    height: wp(12),
    aspectRatio: 1 / 1,
    alignSelf: 'center',
    marginTop: hp(3),
  },
  astroImage: {
    width: wp(12),
    aspectRatio: 1 / 1,
    marginHorizontal: wp(3),
    borderRadius: hp(12),
  },
  line: {
    width: wp(6),
    aspectRatio: 1 / 1,
  },
  close: {
    position: 'absolute',
    right: wp(2),
    top: wp(4),
  },
  // busyBlock: {
  //   height: hp(6),
  //   backgroundColor: '#52361b',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  // },
  busyButton: {
    backgroundColor: '#ffbf00',
    alignItems: 'center',
    paddingVertical: wp(2.5),
    marginTop: wp(2),
    flexDirection: 'row',
    justifyContent: 'center',
    // margin: wp(2),
  },

  //* Edit form with kundali
  inputAddress: {
    flexDirection: 'row',
    alignItems: 'center',
    // borderWidth: 1,
    // borderColor: '#ccc',
    borderRadius: 4,
    paddingHorizontal: wp(2),
    // marginVertical: hp(1),
    backgroundColor: '#f2f1f1',
  },
  linearGradientEdit: {
    height: hp(20),
    justifyContent: 'center',
    borderBottomLeftRadius: wp(5),
    borderBottomRightRadius: wp(5),
    position: 'relative',
    zIndex: 9,
    elevation: 5,
  },
  astroInfoContainerEdit: {
    padding: wp(3),
    marginBottom: hp(2),
    // flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  userNameWord: {
    backgroundColor: '#fffcd5',
    height: wp(12),
    width: wp(12),
    borderRadius: wp(6),
    textAlign: 'center',
    lineHeight: wp(12),
    marginBottom: hp(1),
  },
  userName: {
    fontSize: wp(4),
    fontWeight: '700',
    color: '#fff',
  },
  editProfileButton: {
    backgroundColor: '#fff',
    height: hp(5),
    borderRadius: hp(2.5),
    paddingHorizontal: wp(5),
    justifyContent: 'center',
    // position: 'absolute',
    // top: hp(10),
    // zIndex: 999,
    // marginBottom: hp(-6),
    alignSelf: 'center',
    marginTop: hp(-2.5),
    zIndex: 999,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#fd6c33',
  },
  infoContainerEdit: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // padding: wp(3),
    marginTop: hp(1.5),
  },
  inputContainer: {
    alignItems: 'center',
    // paddingHorizontal: wp(2),
    marginBottom: wp(2),
    backgroundColor: '#f2f1f1',
    paddingHorizontal: wp(3),
    borderRadius: 5,
    height: hp(6),
  },
  label: {
    width: wp(22),
    fontSize: wp(3),
  },
  detailSeparator: {
    width: wp(6),
    fontSize: wp(3),
  },
  info: {
    flex: 1,
    fontSize: wp(3),
    // backgroundColor: '#cccccc80',
    height: hp(5.5),
    paddingHorizontal: wp(3),
  },

  iconRowEdit: {
    width: hp(4),
    aspectRatio: 1 / 1,
    backgroundColor: '#ff9933',
    borderRadius: hp(2),
    textAlign: 'center',
    // lineHeight: hp(4),
    textAlignVertical: 'center',
  },
  radioButtonLabel: {
    fontSize: wp(3.2),
    color: '#444',
    marginLeft: wp(1),
    marginRight: wp(10),
  },
  radioButton: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginLeft: wp(1.5),
  },
  updateButton: {
    width: wp(45),
    backgroundColor: '#fd6c33',
    height: hp(5.5),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
  },
  profileImage: {
    height: wp(15),
    aspectRatio: 1 / 1,
    justifyContent: 'center',
    alignSelf: 'center',
    borderRadius: 5,
    elevation: 5,
  },
  processIcon: {
    width: wp(6),
    aspectRatio: 1 / 1,
    marginRight: wp(2),
  },
});
