import {Dimensions, StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

const dimensions = {
  width: Dimensions.get('window').width,
  height: Dimensions.get('window').height,
};
const {width: screenWidth} = Dimensions.get('window');
export default StyleSheet.create({
  liveCount: {
    color: '#fff',
    marginLeft: wp(1),
    fontWeight: '700',
  },
  liveCount2: {
    color: '#fff',
    fontSize: wp(2.8),
    marginLeft: wp(1),
    fontWeight: '400',
  },
  indicator: {
    backgroundColor: '#ff648a',
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: wp(2),
  },

  max: {
    flex: 1,
    alignItems: 'center',
  },
  backImg: {
    flex: 1,
    width: wp(100),
  },
  buttonHolder: {
    height: 100,
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },

  buttonStyle: {
    position: 'absolute',
    top: wp(2),
    left: wp(3),
    flexDirection: 'row',
    borderWidth: 1,
    backgroundColor: '#00000095',
    borderRadius: 50,
    alignItems: 'center',
  },
  profileButton: {
    // padding: wp(2),
    borderRadius: 50,
  },
  button: {
    padding: wp(1),
    borderRadius: 50,
  },
  buttonAnswer: {
    flexDirection: 'row',
    padding: wp(2),
    borderRadius: 50,
  },
  floatIconContainer: {
    flex: 1,
    // height: wp(3),
    // width: wp(10),
    bottom: 0,
    left: wp(0),
    // right: 0,
    position: 'absolute',
  },
  floatIcon: {
    height: wp(100),
    aspectRatio: 1 / 1,
  },
  graceDialerContainer: {
    // borderRadius: 50,
    width: wp(100),
    backgroundColor: '#a04f06',
    position: 'absolute',
    top: hp(7.5),
    // left: wp(1),
    zIndex: 99999,
  },
  callDialerContainer: {
    borderWidth: 1,
    backgroundColor: '#00000095',
    borderRadius: 50,
    position: 'absolute',
    top: hp(16),
    left: wp(1),
    zIndex: 99999,
  },
  callContainer22: {
    borderWidth: 1,
    borderRadius: 50,
    backgroundColor: '#00000095',
    flexDirection: 'row',
    position: 'absolute',
    top: hp(25),
    left: wp(1),
    zIndex: 999999,
  },
  DialerContainer: {
    flexDirection: 'row',
    padding: wp(2),
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  callIcn3: {
    width: hp(8),
    aspectRatio: 1 / 1,
    borderRadius: 50,
  },
  callContainer21: {
    flexDirection: 'row',
    // position: 'absolute',
    top: hp(12),
    left: wp(1),
    zIndex: 99999,
  },
  callIcn: {
    height: hp(7.3),
    aspectRatio: 1 / 1,
  },
  callIcn2: {
    width: hp(5),
    aspectRatio: 1 / 1,
  },
  buttonEnd: {
    position: 'absolute',
    top: wp(4),
    right: wp(3),
    // padding: wp(2),
    borderRadius: 50,
  },
  buttonBottom: {
    position: 'absolute',
    bottom: 3,
    right: 0,
    padding: wp(2),
    borderRadius: 50,
  },
  buttonText: {
    color: '#fff',
  },
  fullView: {
    width: dimensions.width,
    height: dimensions.height,
  },
  remoteContainer: {
    width: '100%',
    height: 150,
    position: 'absolute',
    // top: 5,
  },
  remote: {
    width: 50,
    height: 50,
    marginHorizontal: 2.5,
  },
  noUserText: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    color: '#0093E9',
  },
  endIcon: {
    height: hp(3.5),
    aspectRatio: 1 / 1,
    borderRadius: hp(2),
  },
  chatContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    // width: wp(100),
    position: 'absolute',
    bottom: 0,
    marginHorizontal: 0,
    padding: wp(2),
    backgroundColor: '#fff',
  },
  input: {
    flex: 1,
    fontSize: wp(3.2),
    color: '#333',
  },
  chatBox: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    // width: wp(70),
    height: hp(5),
    // borderWidth: 1,
    // borderColor: '#6668',
    // backgroundColor: '#00000095',
    // borderRadius: wp(10),
  },
  sndIcon: {
    height: hp(3.5),
    aspectRatio: 1 / 1,
  },
  extContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    // marginLeft: wp(2),
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  extraIcn: {
    // backgroundColor: '#00000095',
    // borderRadius: wp(8),
    // padding: wp(0.7),
    marginLeft: wp(3),
  },
  extIcon: {
    height: hp(4.2),
    aspectRatio: 1 / 1,
  },
  extIcon2: {
    height: hp(3.5),
    aspectRatio: 1 / 1,
  },
  callContainer: {
    position: 'absolute',
    bottom: hp(12),
    right: wp(1),
  },

  ofrContainer: {
    position: 'absolute',
    bottom: hp(22),
    right: 0,
  },
  ofrIcn: {
    height: hp(9),
    aspectRatio: 1 / 1,
  },

  //* chat message message for live chat

  wrapListMessages: {
    position: 'absolute',
    bottom: hp(8),
    left: 0,
    right: 0,
    height: screenWidth / 1.5,
    width: wp(75),
  },
  chatItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: wp(3.5),
    marginVertical: hp(0.5),
  },
  messageItem: {
    flex: 1,
    flexDirection: 'column',
    marginHorizontal: wp(2),
    backgroundColor: '#fff',
    paddingVertical: wp(2),
    paddingHorizontal: wp(2),
    borderRadius: wp(4),
    borderTopLeftRadius: 0,
  },
  avatar: {
    borderRadius: hp(2.5),
    height: hp(5),
    aspectRatio: 1 / 1,
  },
  name: {
    fontSize: wp(2.5),
    color: '#333',
  },
  content: {
    // flex: 1,
    fontSize: wp(3.5),
    fontWeight: '700',
    marginTop: 3,
    color: '#333',
  },

  //*popup screen
  followouter: {
    justifyContent: 'center',
    alignItems: 'center',
    width: wp(20),
    paddingHorizontal: wp(3),
    height: hp(4),
    borderRadius: hp(2),
    // backgroundColor: 'dodgerblue',
    borderColor: '#fff',
    // backgroundColor: '#bc0f17',
    backgroundColor: '#fff',
    // marginTop: wp(5),
  },
  unfollowouter: {
    justifyContent: 'center',
    alignItems: 'center',
    width: wp(20),
    paddingHorizontal: wp(3),
    height: hp(4),
    borderRadius: hp(2),
    borderWidth: 1,
    borderColor: '#fff',
    // backgroundColor: '#fff',
  },
  oldPrice: {
    fontSize: wp(3),
    color: '#a04f06',
    textDecorationLine: 'line-through',
    marginHorizontal: wp(1),
  },
  newPrice: {
    fontSize: wp(3),
    color: '#fffcd5',
    fontWeight: '700',
    marginHorizontal: wp(1),
  },
  linearGradient: {
    height: hp(25),
    borderBottomRightRadius: wp(10),
    justifyContent: 'center',
  },
  astroInfoContainer: {
    padding: wp(3),
    marginBottom: hp(8),
    flexDirection: 'row',
    alignItems: 'center',
  },
  astroPhoto: {
    width: wp(18),
    aspectRatio: 1 / 1,
    borderRadius: wp(9),
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    marginRight: wp(2),
  },
  astroName: {
    fontSize: wp(4),
    fontWeight: '700',
    color: '#fff',
    marginBottom: wp(1),
  },
  followButton: {
    height: hp(4),
    backgroundColor: '#fff',
    borderRadius: hp(2),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: wp(3),
  },
  postButton: {
    height: hp(4),
    borderColor: '#fff',
    borderWidth: 1,
    borderRadius: hp(2),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: wp(3),
    marginLeft: wp(2),
  },
  infoContainer: {
    backgroundColor: '#fff',
    elevation: 5,
    flexDirection: 'row',
    paddingVertical: wp(5),
    marginHorizontal: wp(3),
    marginBottom: wp(3),
    marginTop: hp(-8),
    borderRadius: 5,
  },
  value: {
    fontSize: wp(5.5),
    fontWeight: '700',
    color: '#fd6c33',
    marginBottom: wp(1),
  },

  headings: {
    fontSize: wp(4),
    fontWeight: '700',
    color: '#333',
    marginBottom: wp(1),
  },
  VerifiedContainer: {
    // backgroundColor: '#fd6c33',
    // width: wp(5),
    // height: wp(10),
    // aspectRatio: 1 / 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verifiedIcon: {
    // backgroundColor: '#fd6c33',
    // width: wp(5),
    height: wp(10),
    aspectRatio: 1 / 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  separator: {
    width: wp(2),
  },
  reviewSeparator: {
    height: 1,
    backgroundColor: '#00000020',
    marginVertical: wp(1),
  },
  chatButton: {
    backgroundColor: '#fd6c33',
    height: hp(7),
    alignItems: 'center',
  },
  callButton: {
    backgroundColor: '#fd8933',
    height: hp(7),
    alignItems: 'center',
  },
  iconRow: {
    marginRight: wp(2),
  },
  modalContainer: {
    backgroundColor: '#00000080',
    position: 'absolute',
    top: 0,
    width: '100%',
    height: '100%',
    // justifyContent: 'flex-start',
    zIndex: 9999999.99,
  },
  screenContainer: {
    backgroundColor: '#fd6c33',
    position: 'absolute',
    top: 0,
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
  },
  screenContainer2: {
    flex: 1,
  },
  popupContainer: {
    backgroundColor: '#fff',
    // height: hp(40),
    width: wp(94),
    alignSelf: 'center',
    borderRadius: wp(3),
    padding: wp(3),
    marginTop: hp(10),
  },
  popupKundaliContainer: {
    backgroundColor: '#fff',
    height: hp(55),
    borderTopLeftRadius: wp(3),
    borderTopRightRadius: wp(3),
    padding: wp(3),
  },

  popupContainer2: {
    backgroundColor: '#00000080',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },

  mainContent: {
    backgroundColor: '#fff',
    height: hp(70),
    width: wp(80),
    borderRadius: wp(3),
    padding: wp(3),
  },
  listContainerMain: {
    // borderWidth: 1,
    borderColor: '#cccccc',
    padding: wp(2),
    marginTop: wp(3),
    marginBottom: 'auto',
  },
  listContainerMain2: {
    borderWidth: 1,
    borderColor: '#cccccc',
    padding: wp(2),
    marginTop: wp(3),
    // marginBottom: 'auto',
    alignItems: 'center',
  },
  listContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp(2),
    paddingVertical: wp(1),
  },
  popupButton: {
    flex: 1,
    // backgroundColor: '#bc0f17',
    backgroundColor: '#2f8a0f',
    padding: wp(3),
    // marginTop: hp(10),
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  popupButton2: {
    flex: 1,
    backgroundColor: '#bc0f17',
    padding: wp(3),
    // marginTop: hp(10),
    flexDirection: 'row',
    justifyContent: 'center',
  },
  popupButtonText: {
    color: '#fff',
    fontSize: wp(3.5),
    fontWeight: '700',
  },
  allSetIcon: {
    height: wp(12),
    aspectRatio: 1 / 1,
    alignSelf: 'center',
    marginTop: hp(3),
  },
  astroImage: {
    width: wp(12),
    aspectRatio: 1 / 1,
    marginHorizontal: wp(3),
    borderRadius: hp(12),
  },
  line: {
    width: wp(6),
    aspectRatio: 1 / 1,
  },
  close: {
    position: 'absolute',
    right: wp(2),
    top: wp(4),
  },
  // busyBlock: {
  //   height: hp(6),
  //   backgroundColor: '#52361b',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  // },
  busyButton: {
    backgroundColor: '#ffbf00',
    alignItems: 'center',
    paddingVertical: wp(2.5),
    marginTop: wp(2),
    flexDirection: 'row',
    justifyContent: 'center',
    // margin: wp(2),
  },
});
