import {StyleSheet} from 'react-native';
import {color, appStyle} from '../../utility';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
export default StyleSheet.create({
  chatContainer: {
    backgroundColor: '#f2f1f1',
    borderRadius: 20,
    borderBottomLeftRadius: 0,
    marginLeft: 15,
    marginRight: 15,
    // elevation: 8,
  },
  chatTxt: {
    color: color.BLACK,
    fontSize: wp(3.2),
    marginVertical: 5,
    fontWeight: '500',
    paddingHorizontal: 12,
    paddingVertical: 3,
  },
  dateTxt: {
    color: color.BLACK,
    fontSize: wp(3.2),
    marginTop: wp(0.5),
    textAlign: 'left',
    fontWeight: '500',
    paddingHorizontal: 12,
    // paddingVertical: 3,
  },
  arrowRight: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 8,
    borderRightWidth: 0,
    borderBottomWidth: 10,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#fff',
    transform: [{rotate: '-90deg'}],
    position: 'absolute',
    left: -8,
    top: -1.1,
  },
  arrowLeft: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 0,
    borderRightWidth: 8,
    borderBottomWidth: 10,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#ff417b',
    transform: [{rotate: '90deg'}],
    position: 'absolute',
    right: -6,
    top: -1.1,
  },
});
